[package]
name = "imath-sys"
version = "0.1.0"
authors = ["Declan Kelly <thedeck@amazon.com>"]
edition = "2018"
readme = "README.md"

build = "build.rs"

[dependencies]

[build-dependencies]
cc = "1.0.46"
