[package]
name = "imath-sys"
version = "0.1.0"
authors = ["Declan Kelly <thedeck@amazon.com>"]
edition = "2018"
readme = "README.md"

build = "build.rs"
links = "imath"

[dependencies]

[build-dependencies]
cc = "1.0.46"
bindgen = "0.51.1"
