(function() {var implementors = {};
implementors["imath_sys"] = [{"text":"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"imath_sys/struct.mpz_t.html\" title=\"struct imath_sys::mpz_t\">mpz_t</a>","synthetic":true,"types":["imath_sys::mpz_t"]},{"text":"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"imath_sys/struct.mpq_t.html\" title=\"struct imath_sys::mpq_t\">mpq_t</a>","synthetic":true,"types":["imath_sys::mpq_t"]}];
implementors["reckoner"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"reckoner/enum.Error.html\" title=\"enum reckoner::Error\">Error</a>","synthetic":true,"types":["reckoner::error::Error"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"reckoner/enum.RoundMode.html\" title=\"enum reckoner::RoundMode\">RoundMode</a>","synthetic":true,"types":["reckoner::rational::RoundMode"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"reckoner/struct.Integer.html\" title=\"struct reckoner::Integer\">Integer</a>","synthetic":false,"types":["reckoner::integer::Integer"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"reckoner/struct.Rational.html\" title=\"struct reckoner::Rational\">Rational</a>","synthetic":false,"types":["reckoner::rational::Rational"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()