python scripts/generate_integer_ops.py generate/op_descriptions/integer/addition_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/addition.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/division_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/division.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/multiplication_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/multiplication.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/remainder_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/remainder.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/subtraction_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/integer/subtraction.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/addition_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/addition.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/division_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/division.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/multiplication_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/multiplication.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/subtraction_assign.json generate/templates/ src/
python scripts/generate_integer_ops.py generate/op_descriptions/rational/subtraction.json generate/templates/ src/