name: Rust

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Test on platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        token: ${{ secrets.GitHub_PAT }} // `GitHub_PAT` is a secret contains your PAT.
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
